/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ApplyStyle {

    }
  }

  interface HTMLApplyStyleElement extends StencilComponents.ApplyStyle, HTMLStencilElement {}

  var HTMLApplyStyleElement: {
    prototype: HTMLApplyStyleElement;
    new (): HTMLApplyStyleElement;
  };
  interface HTMLElementTagNameMap {
    'apply-style': HTMLApplyStyleElement;
  }
  interface ElementTagNameMap {
    'apply-style': HTMLApplyStyleElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'apply-style': JSXElements.ApplyStyleAttributes;
    }
  }
  namespace JSXElements {
    export interface ApplyStyleAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StencilButtonShadow {

    }
  }

  interface HTMLStencilButtonShadowElement extends StencilComponents.StencilButtonShadow, HTMLStencilElement {}

  var HTMLStencilButtonShadowElement: {
    prototype: HTMLStencilButtonShadowElement;
    new (): HTMLStencilButtonShadowElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-button-shadow': HTMLStencilButtonShadowElement;
  }
  interface ElementTagNameMap {
    'stencil-button-shadow': HTMLStencilButtonShadowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stencil-button-shadow': JSXElements.StencilButtonShadowAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilButtonShadowAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;