/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface StencilCard {

    }
  }

  interface HTMLStencilCardElement extends StencilComponents.StencilCard, HTMLStencilElement {}

  var HTMLStencilCardElement: {
    prototype: HTMLStencilCardElement;
    new (): HTMLStencilCardElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-card': HTMLStencilCardElement;
  }
  interface ElementTagNameMap {
    'stencil-card': HTMLStencilCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stencil-card': JSXElements.StencilCardAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilCardAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StencilUsers {

    }
  }

  interface HTMLStencilUsersElement extends StencilComponents.StencilUsers, HTMLStencilElement {}

  var HTMLStencilUsersElement: {
    prototype: HTMLStencilUsersElement;
    new (): HTMLStencilUsersElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-users': HTMLStencilUsersElement;
  }
  interface ElementTagNameMap {
    'stencil-users': HTMLStencilUsersElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stencil-users': JSXElements.StencilUsersAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilUsersAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;