/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface StencilTodoitem {
      'completed': boolean;
      'text': string;
      'uid': number;
    }
  }

  interface HTMLStencilTodoitemElement extends StencilComponents.StencilTodoitem, HTMLStencilElement {}

  var HTMLStencilTodoitemElement: {
    prototype: HTMLStencilTodoitemElement;
    new (): HTMLStencilTodoitemElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-todoitem': HTMLStencilTodoitemElement;
  }
  interface ElementTagNameMap {
    'stencil-todoitem': HTMLStencilTodoitemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stencil-todoitem': JSXElements.StencilTodoitemAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilTodoitemAttributes extends HTMLAttributes {
      'completed'?: boolean;
      'text'?: string;
      'uid'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StencilTodolist {

    }
  }

  interface HTMLStencilTodolistElement extends StencilComponents.StencilTodolist, HTMLStencilElement {}

  var HTMLStencilTodolistElement: {
    prototype: HTMLStencilTodolistElement;
    new (): HTMLStencilTodolistElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-todolist': HTMLStencilTodolistElement;
  }
  interface ElementTagNameMap {
    'stencil-todolist': HTMLStencilTodolistElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stencil-todolist': JSXElements.StencilTodolistAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilTodolistAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;